name = "trivia-ops"
pages_build_output_dir = "dist"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "trivia_ops"
database_id = "f9a06e72-f6a8-4914-973c-de0e45226da2"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "trivia-ops-media"

[vars]
SESSION_TTL_HOURS = "24"
